[project]
name = "ingdatos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "empiricaldist>=0.9.0",
    "ipykernel>=7.2.0",
    "missingno>=0.5.2",
    "nbformat>=5.10.4",
    "pandas>=3.0.1",
    "plotly>=6.6.0",
    "pyjanitor>=0.32.20",
    "pyreadr>=0.5.4",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "upsetplot>=0.9.0",
]
